In [36]:
import numpy as np


In [37]:
ar=np.array([22,33,44,55])

In [38]:
ar
ar[2]

44

In [39]:
type(ar)

numpy.ndarray

In [40]:
n1= np.zeros((1,2))

In [41]:
n1

array([[0., 0.]])

In [42]:
n3=np.zeros((6,6))
n3

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [43]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
np.column_stack((a1,a2))


array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 6])

In [45]:
np.vstack((a1,a2))

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
import pandas as pd

In [47]:
seriesObject=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
seriesObject


a    1
b    2
c    3
d    4
e    5
dtype: int64

In [48]:
#Dictionary to series object
d1={'a':1,'b':2,'c':3}
d1

{'a': 1, 'b': 2, 'c': 3}

In [49]:
SO=pd.Series(d1)
SO

a    1
b    2
c    3
dtype: int64

In [50]:
#data frame

student ={'student_name':['vardaan','kanika','mahima','lakshit'],'student_marks':[100,95,90,85]}
pd.DataFrame(student)




student_name  student_marks
0      vardaan            100
1       kanika             95
2       mahima             90
3      lakshit             85

In [51]:
iris = pd.read_csv('iris.csv')
iris.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [52]:
iris[(iris['sepal.length']>5)]

sepal.length  sepal.width  petal.length  petal.width     variety
0             5.1          3.5           1.4          0.2      Setosa
5             5.4          3.9           1.7          0.4      Setosa
10            5.4          3.7           1.5          0.2      Setosa
14            5.8          4.0           1.2          0.2      Setosa
15            5.7          4.4           1.5          0.4      Setosa
16            5.4          3.9           1.3          0.4      Setosa
17            5.1          3.5           1.4          0.3      Setosa
18            5.7          3.8           1.7          0.3      Setosa
19            5.1          3.8           1.5          0.3      Setosa
20            5.4          3.4           1.7          0.2      Setosa
21            5.1          3.7           1.5          0.4      Setosa
23            5.1          3.3           1.7          0.5      Setosa
27            5.2          3.5           1.5          0.2      Setosa
28            5.2          3.4           1.4          0.2      Setosa
31            5.4          3.4           1.5          0.4      Setosa
32            5.2          4.1           1.5          0.1      Setosa
33            5.5          4.2           1.4          0.2      Setosa
36            5.5          3.5           1.3          0.2      Setosa
39            5.1          3.4           1.5          0.2      Setosa
44            5.1          3.8           1.9          0.4      Setosa
46            5.1          3.8           1.6          0.2      Setosa
48            5.3          3.7           1.5          0.2      Setosa
50            7.0          3.2           4.7          1.4  Versicolor
51            6.4          3.2           4.5          1.5  Versicolor
52            6.9          3.1           4.9          1.5  Versicolor
53            5.5          2.3           4.0          1.3  Versicolor
54            6.5          2.8           4.6          1.5  Versicolor
55            5.7          2.8           4.5          1.3  Versicolor
56            6.3          3.3           4.7          1.6  Versicolor
58            6.6          2.9           4.6          1.3  Versicolor
..            ...          ...           ...          ...         ...
120           6.9          3.2           5.7          2.3   Virginica
121           5.6          2.8           4.9          2.0   Virginica
122           7.7          2.8           6.7          2.0   Virginica
123           6.3          2.7           4.9          1.8   Virginica
124           6.7          3.3           5.7          2.1   Virginica
125           7.2          3.2           6.0          1.8   Virginica
126           6.2          2.8           4.8          1.8   Virginica
127           6.1          3.0           4.9          1.8   Virginica
128           6.4          2.8           5.6          2.1   Virginica
129           7.2          3.0           5.8          1.6   Virginica
130           7.4          2.8           6.1          1.9   Virginica
131           7.9          3.8           6.4          2.0   Virginica
132           6.4          2.8           5.6          2.2   Virginica
133           6.3          2.8           5.1          1.5   Virginica
134           6.1          2.6           5.6          1.4   Virginica
135           7.7          3.0           6.1          2.3   Virginica
136           6.3          3.4           5.6          2.4   Virginica
137           6.4          3.1           5.5          1.8   Virginica
138           6.0          3.0           4.8          1.8   Virginica
139           6.9          3.1           5.4          2.1   Virginica
140           6.7          3.1           5.6          2.4   Virginica
141           6.9          3.1           5.1          2.3   Virginica
142           5.8          2.7           5.1          1.9   Virginica
143           6.8          3.2           5.9          2.3   Virginica
144           6.7          3.3           5.7          2.5   Virginica
145           6

In [53]:
iris.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [54]:
iris.head(20) #if no parameter is passed it is 5 

sepal.length  sepal.width  petal.length  petal.width variety
0            5.1          3.5           1.4          0.2  Setosa
1            4.9          3.0           1.4          0.2  Setosa
2            4.7          3.2           1.3          0.2  Setosa
3            4.6          3.1           1.5          0.2  Setosa
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa

In [55]:
iris.tail()

sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [56]:
iris.shape

(150, 5)

In [57]:
iris.iloc[[2,3,4,7],[0,3]]

sepal.length  petal.width
2           4.7          0.2
3           4.6          0.2
4           5.0          0.2
7           5.0          0.2

In [58]:
iris.iloc[2:8,0:3]

sepal.length  sepal.width  petal.length
2           4.7          3.2           1.3
3           4.6          3.1           1.5
4           5.0          3.6           1.4
5           5.4          3.9           1.7
6           4.6          3.4           1.4
7           5.0          3.4           1.5

In [59]:
#same as iloc , only used to extract data by label name 

In [60]:
iris.loc[0:9,('variety','sepal.length')]

variety  sepal.length
0  Setosa           5.1
1  Setosa           4.9
2  Setosa           4.7
3  Setosa           4.6
4  Setosa           5.0
5  Setosa           5.4
6  Setosa           4.6
7  Setosa           5.0
8  Setosa           4.4
9  Setosa           4.9

In [71]:
long_versicolor =iris[(iris['sepal.length']>5) & (iris['variety']=='Versicolor')]
long_versicolor

sepal.length  sepal.width  petal.length  petal.width     variety
50           7.0          3.2           4.7          1.4  Versicolor
51           6.4          3.2           4.5          1.5  Versicolor
52           6.9          3.1           4.9          1.5  Versicolor
53           5.5          2.3           4.0          1.3  Versicolor
54           6.5          2.8           4.6          1.5  Versicolor
55           5.7          2.8           4.5          1.3  Versicolor
56           6.3          3.3           4.7          1.6  Versicolor
58           6.6          2.9           4.6          1.3  Versicolor
59           5.2          2.7           3.9          1.4  Versicolor
61           5.9          3.0           4.2          1.5  Versicolor
62           6.0          2.2           4.0          1.0  Versicolor
63           6.1          2.9           4.7          1.4  Versicolor
64           5.6          2.9           3.6          1.3  Versicolor
65           6.7          3.1           4.4          1.4  Versicolor
66           5.6          3.0           4.5          1.5  Versicolor
67           5.8          2.7           4.1          1.0  Versicolor
68           6.2          2.2           4.5          1.5  Versicolor
69           5.6          2.5           3.9          1.1  Versicolor
70           5.9          3.2           4.8          1.8  Versicolor
71           6.1          2.8           4.0          1.3  Versicolor
72           6.3          2.5           4.9          1.5  Versicolor
73           6.1          2.8           4.7          1.2  Versicolor
74           6.4          2.9           4.3          1.3  Versicolor
75           6.6          3.0           4.4          1.4  Versicolor
76           6.8          2.8           4.8          1.4  Versicolor
77           6.7          3.0           5.0          1.7  Versicolor
78           6.0          2.9           4.5          1.5  Versicolor
79           5.7          2.6           3.5          1.0  Versicolor
80           5.5          2.4           3.8          1.1  Versicolor
81           5.5          2.4           3.7          1.0  Versicolor
82           5.8          2.7           3.9          1.2  Versicolor
83           6.0          2.7           5.1          1.6  Versicolor
84           5.4          3.0           4.5          1.5  Versicolor
85           6.0          3.4           4.5          1.6  Versicolor
86           6.7          3.1           4.7          1.5  Versicolor
87           6.3          2.3           4.4          1.3  Versicolor
88           5.6          3.0           4.1          1.3  Versicolor
89           5.5          2.5           4.0          1.3  Versicolor
90           5.5          2.6           4.4          1.2  Versicolor
91           6.1          3.0           4.6          1.4  Versicolor
92           5.8          2.6           4.0          1.2  Versicolor
94           5.6          2.7           4.2          1.3  Versicolor
95           5.7          3.0           4.2          1.2  Versicolor
96           5.7          2.9           4.2          1.3  Versicolor
97           6.2          2.9           4.3          1.3  Versicolor
98           5.1          2.5           3.0          1.1  Versicolor
99           5.7          2.8           4.1          1.3  Versicolor

In [17]:
from array  import *

In [26]:
x=array([7,9,4])

TypeError: array() argument 1 must be a unicode character, not list

In [21]:
x

array('i', [7, 9, 4])

In [22]:
x=[2,4,6]
x

[2, 4, 6]

In [24]:
x*2

[2, 4, 6, 2, 4, 6]